set(_CATKIN_CURRENT_PACKAGE "subscriber_node")
set(subscriber_node_VERSION "0.0.0")
set(subscriber_node_MAINTAINER "sven <sven@todo.todo>")
set(subscriber_node_PACKAGE_FORMAT "2")
set(subscriber_node_BUILD_DEPENDS "rospy")
set(subscriber_node_BUILD_EXPORT_DEPENDS "rospy")
set(subscriber_node_BUILDTOOL_DEPENDS "catkin")
set(subscriber_node_BUILDTOOL_EXPORT_DEPENDS )
set(subscriber_node_EXEC_DEPENDS "rospy")
set(subscriber_node_RUN_DEPENDS "rospy")
set(subscriber_node_TEST_DEPENDS )
set(subscriber_node_DOC_DEPENDS )
set(subscriber_node_URL_WEBSITE "")
set(subscriber_node_URL_BUGTRACKER "")
set(subscriber_node_URL_REPOSITORY "")
set(subscriber_node_DEPRECATED "")